#!/bin/bash

# Homebrew
ruby -e "$(curl -fsSL https://raw.github.com/Homebrew/homebrew/go/install)"

#Install pep8 and pylint for syntax/convetion checks and nose for unit testing

sudo easy_install pip
sudo pip install pep8 pylint pyflakes nose

#Remove old config files
rm -f ~/.vim
rm -f ~/.vimrc
rm -f ~/.gvimrc
rm -f ~/.bashrc
rm -f ~/.zshrc
rm -f ~/.screenrc

#Create symlinks

ln -s ~/dotfiles/dotvim ~/.vim
ln -s ~/dotfiles/vimrc ~/.vimrc
ln -s ~/dotfiles/gvimrc ~/.gvimrc
ln -s ~/dotfiles/bashrc ~/.bashrc
ln -s ~/dotfiles/zshrc-mac ~/.zshrc
ln -s ~/dotfiles/screenrc ~/.screenrc

ln -s ~/dotfiles/bin ~/bin

~/dotfiles/bin/vcprompt-install

#Load submodules

cd ~/dotfiles
git submodule init
git submodule update

#Create tmp folder
mkdir -p ~/tmp/vim_bak

#RVM
\curl -sSL https://get.rvm.io | bash -s stable --ruby

#build command-T plugin - this may cause a segfault depending on the ruby version
#see http://blog.hugeaim.com/2012/05/03/fix-command-t-segv-fault-in-vim/ to fix
cd ~/dotfiles/dotvim/bundle/CommandT/
rake make

touch ~/.profile

#Nodejs
brew install node
