#!/bin/bash

rm -f ~/.vim
rm -f ~/.vimrc
rm -f ~/.gvimrc
rm -f ~/.bashrc
rm -f ~/.zshrc
rm -f ~/.screenrc

#Create symlinks

ln -s ~/dotfiles/dotvim ~/.vim
ln -s ~/dotfiles/gitconfig ~/.gitconfig
ln -s ~/dotfiles/vimrc ~/.vimrc
ln -s ~/dotfiles/gvimrc ~/.gvimrc
#ln -s ~/dotfiles/bashrc ~/.bashrc # not working correctly, using zsh
ln -s ~/dotfiles/zshrc ~/.zshrc
ln -s ~/dotfiles/screenrc ~/.screenrc

ln -s ~/dotfiles/bin ~/bin

~/dotfiles/bin/vcprompt-install

#Load submodules

cd ~/dotfiles
git submodule init
git submodule update

#Create tmp folder
mkdir -p ~/tmp/vim_bak

#Install pep8 and pylint for syntax/convetion checks and nose for unit testing

sudo apt-get install python-pip
sudo pip install pep8 pylint pyflakes nose flake8

#Install ruby enabled vim
sudo apt-get purge vim
sudo apt-get install vim-nox ruby rake rubygems ruby-dev

#RVM
\curl -sSL https://get.rvm.io | bash -s stable --ruby

#build command-T plugin - this may cause a segfault depending on the ruby version
#see http://blog.hugeaim.com/2012/05/03/fix-command-t-segv-fault-in-vim/ to fix
cd ~/dotfiles/dotvim/bundle/CommandT/
rake make
